### ISSUE TITLE
AP01 - Impossível deletar root

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#23]
Quando criado uma nova feature, cria-se uma associação com a root, depois disso, ao tentar remover a root, o sistema congela.

**Comment by lucianoMarchezan** [comment]
erro está em parseModelToString(), linha 44

**Comment by Ferfortlima** [comment]
Agora tá dando outro erro.

![captura de tela 2017-05-13 as 16 03 22](https://cloud.githubusercontent.com/assets/22458748/26028406/0a43e29a-37f6-11e7-8ee8-f50106c099dc.png)
