### ISSUE TITLE
AP04 - Problema com features fantasmas

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#26]
Adiciono uma terceira feature como filha da 2º feature, removo a 2º. Restam a 1º e 3º features sem relacionamento. Tento adicionar uma feature novamente, com o mesmo nome de uma das features existentes. Informa que já existe uma feature com o mesmo nome e não adiciona, Depois disso, toda a feature que eu tentar adicionar vai ser informado o erro na tela

**Comment by lucianoMarchezan** [comment]
erro no ParseScript.js, linha 44 novamente

**Comment by Ferfortlima** [comment]
agora o erro não está mais no parser

![captura de tela 2017-05-13 as 16 07 42](https://cloud.githubusercontent.com/assets/22458748/26028433/9190e14e-37f6-11e7-9fbf-d58c89d5216d.png)
