### ISSUE TITLE
AP06 - Remoção da "child" remove "root" também

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#28]
Quando removido a feature filha da root, automaticamente está sendo removido a feature root junto.

**Comment by lucianoMarchezan** [comment]
parseModelToString está colocando uma virgula onde não deveria 

![image](https://cloud.githubusercontent.com/assets/22458623/26028001/4bc95b62-37ee-11e7-82e5-a84a154b532f.png)
