### ISSUE TITLE
AP09 - Sistema congela ao mudar para opcional

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#31]
Cria-se uma arvore com várias features. Ao remover a feature pai e deixar as filhas sem associações, mudou-se essas features que sobraram para opcional, e o sistema travou.

**Comment by lucianoMarchezan** [comment]
problema no ParseScript, linha 44, de novo

**Comment by Ferfortlima** [comment]
para de ficar apontando meu parser toda hora :(      já foi resolvido :)
