### ISSUE TITLE
AP13 - Falta de feedback para features sem associação

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#35]
Features sem associação não podem ser definidas como mandatórias, opcionais, etc. Mas caso o usuário selecione, o sistema não informa nada, mas nada acontece (aparentemente).

**Comment by lucianoMarchezan** [comment]
Na verdade, o tipo "mandatorio", "optional" ou "alternativo" são relacionados a ambos: feature e relação. Sendo assim, uma feature que não está relacionada a outra não pode ser nenhum dos 3 tipos. Porém, quando a associação é criada, o tipo aparecerá. Então acredito que não é algo que deva ser corrigido :+1:
