### ISSUE TITLE
AP18 - Erro por conta do nome ROOT

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#40]
Sobre o programa travar só acontece quando o nome da feature é root , se renomear a mesma e excluir o travamento não acontece e atualiza normalmente

**Comment by lucianoMarchezan** [comment]
Não sei quem fez isso, mas aqui não resolveu o problema

**Comment by Ferfortlima** [comment]
O problema foi resolvido junto com a AP01.
