### ISSUE TITLE
AP23 - Features Fantasmas na lista de child

### ISSUE THREAD

**Issue by Ferfortlima** [HestiaProject/Atlas#45]
Quando se cria mais features, faz associações entre elas e a root e depois deleta a root, se vai criar novas associações fica alguma fantasma na lista sem child e a janela de associação nem abre.

![captura de tela 2017-05-15 as 11 30 43](https://cloud.githubusercontent.com/assets/22458748/26062695/f845b65a-3961-11e7-989b-64c63904f7ce.png)

**Comment by lucianoMarchezan** [comment]
Corrigido!
